# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i6H1zt446WnEXMFtsvHQOl-JyeaRR4bT
"""

import json, boto3, re, uuid, os
from io import BytesIO
from PyPDF2 import PdfReader
from pymongo import MongoClient
from datetime import datetime

s3 = boto3.client("s3")

# ---------------- MONGODB ----------------
client = MongoClient(os.environ["MONGO_URI"])
db = client["resume_ai"]
resumes = db["resumes"]

# ---------------- PARSE RESUME ----------------
def parse_resume(text):
    text_l = text.lower()

    # -------- EMAIL --------
    email = re.findall(
        r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}",
        text
    )

    # -------- SKILLS (EXTENDED – DOMAIN AWARE) --------
    skills_db = [
        # IT
        "python", "sql", "aws", "docker", "spark", "machine learning",
        # Mechanical
        "autocad", "solid works", "solidworks", "ms office",
        "production", "design", "quality", "maintenance"
    ]

    skills = []
    for s in skills_db:
        if s in text_l:
            skills.append(s.upper())

    # -------- EDUCATION (CLEAN OUTPUT) --------
    education = []

    if "bachelor of engineering" in text_l or "b.e" in text_l or "be(" in text_l:
        education.append("B.E (Bachelor of Engineering)")

    if "mechanical" in text_l:
        education.append("Mechanical Engineering")

    if "bachelor of technology" in text_l or "b.tech" in text_l:
        education.append("B.Tech")

    if "master" in text_l or "m.tech" in text_l:
        education.append("Post Graduation")

    return {
        "email": email[0] if email else None,
        "skills": list(set(skills)),
        "education": list(set(education))
    }

# ---------------- API HANDLER ----------------
def handle_api_request():
    print("🔄 Job refresh triggered via API")

    return {
        "statusCode": 200,
        "headers": {"Content-Type": "application/json"},
        "body": json.dumps({"message": "Jobs refreshed successfully"})
    }

# ---------------- S3 HANDLER ----------------
def handle_s3_event(event):
    rec = event["Records"][0]
    bucket = rec["s3"]["bucket"]["name"]
    key = rec["s3"]["object"]["key"]

    if not key.lower().endswith(".pdf"):
        return {"statusCode": 200}

    obj = s3.get_object(Bucket=bucket, Key=key)
    reader = PdfReader(BytesIO(obj["Body"].read()))

    text = ""
    for p in reader.pages:
        if p.extract_text():
            text += p.extract_text() + "\n"

    parsed = parse_resume(text)

    resumes.insert_one({
        "user_id": str(uuid.uuid4()),
        "resume_text": text,
        "email": parsed["email"],
        "skills": parsed["skills"],
        "education": parsed["education"],
        "created_at": datetime.utcnow()
    })

    print("✅ Resume parsed & stored")
    return {"statusCode": 200}

# ---------------- MAIN HANDLER ----------------
def lambda_handler(event, context):
    try:
        # API Gateway trigger
        if "requestContext" in event:
            return handle_api_request()

        # S3 trigger
        if "Records" in event:
            return handle_s3_event(event)

        return {
            "statusCode": 400,
            "body": "Unknown event source"
        }

    except Exception as e:
        print("❌ ERROR:", str(e))
        return {
            "statusCode": 500,
            "body": str(e)
        }