# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i6H1zt446WnEXMFtsvHQOl-JyeaRR4bT

## PROJECT FOLDER STRUCTURE:-
"""

intelligent-resume-job-recommender/
│
├── lambda/
│   ├── resume_parser_lambda.py
│   ├── job_refresh_lambda.py
│   └── requirements.txt
│
├── streamlit/
│   ├── app.py
│   ├── app_with_refresh.py
│   └── requirements.txt
│
├── architecture/
│   ├── architecture_diagram.png
│   └── sequence_flow.png
│
├── ppt/
│   └── Project_Presentation.pptx
│
├── docs/
│   ├── Project_Report.pdf
│   └── Deployment_Guide.md
│
├── .gitignore
├── README.md