# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i6H1zt446WnEXMFtsvHQOl-JyeaRR4bT
"""

import streamlit as st
import boto3
from datetime import datetime

# -------- CONFIG --------
S3_BUCKET_NAME = "resume-ai-project-bucket"
AWS_REGION = "us-east-1"

# AWS S3 client (NO profile_name)
s3 = boto3.client("s3", region_name=AWS_REGION)

# -------- UI --------
st.set_page_config(page_title="AI Resume Upload", layout="centered")
st.title("📄 Resume Upload Portal")

st.write("Upload your resume (PDF or DOCX). It will be securely stored in AWS S3.")

uploaded_file = st.file_uploader(
    "Choose your resume file",
    type=["pdf", "docx"]
)

if uploaded_file is not None:
    file_name = uploaded_file.name
    file_type = uploaded_file.type
    upload_time = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")

    st.write("### File Details")
    st.write("**Filename:**", file_name)
    st.write("**File Type:**", file_type)
    st.write("**Upload Time (UTC):**", upload_time)

    if st.button("Upload to S3"):
        try:
            s3.put_object(
                Bucket=S3_BUCKET_NAME,
                Key=f"resumes/{file_name}",
                Body=uploaded_file.getvalue(),
                Metadata={
                    "upload_time": upload_time,
                    "file_type": file_type
                }
            )
            st.success("✅ Resume successfully uploaded to AWS S3!")
        except Exception as e:
            st.error(f"❌ Upload failed: {e}")